(fix) Enforce FoliatedTriangulation class invariant
The FoliatedTriangulation class invariant is that the timevalues and cell types stored in the vertices and cells of the Delaunay triangulation must correct.

The initialization order of the data members was re-arranged so that the triangulation, foliation initial radius, and foliation spacing were initialized first. This allows the vertices to be checked and corrected, and they are initialized next. Once the vertices have the correct timevalues, the cells can be initialized with the correct cell types. All other containers of edges and faces (sub-simplices) derive from the vertices and cells.

Also update to vcpkgGitCommitId: ae59b93af0c1dce4126e963fca5b330662495fa1

diff --git a/.github/workflows/codecov-upload.yml b/.github/workflows/codecov-upload.yml
--- a/.github/workflows/codecov-upload.yml
+++ b/.github/workflows/codecov-upload.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Restore artifacts or setup vcpkg
         uses: lukka/run-vcpkg@v10
         with:
-          vcpkgGitCommitId: a7b6122f6b6504d16d96117336a0562693579933
+          vcpkgGitCommitId: ae59b93af0c1dce4126e963fca5b330662495fa1
 
       - name: Configure
         run: cmake -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D ENABLE_TESTING:BOOL=TRUE -D ENABLE_COVERAGE:BOOL=TRUE -S . -B build
@@ -38,22 +38,25 @@ jobs:
         working-directory: build
         run: ctest --output-on-failure -j 2
 
-      - name: Generate coverage info
-        working-directory: build
-        continue-on-error: true
-        run: |
-          mkdir gcov-reports
-          pushd gcov-reports
-          for f in `find ../tests/CMakeFiles/CDT_test.dir -name '*.o'`; do
-            echo "Processing $f file..."
-            gcov -o ${f} x
-          done
-          ls | wc -l
-          popd
+      - name: collect code coverage
+        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
 
-      - name: Submit to codecov.io
-        uses: codecov/codecov-action@v3
-        with:
-          directory: build/gcov-reports
-          fail_ci_if_error: false
-          verbose: true
+#      - name: Generate coverage info
+#        working-directory: build
+#        continue-on-error: true
+#        run: |
+#          mkdir gcov-reports
+#          pushd gcov-reports
+#          for f in `find ../tests/CMakeFiles/CDT_test.dir -name '*.o'`; do
+#            echo "Processing $f file..."
+#            gcov -o ${f} x
+#          done
+#          ls | wc -l
+#          popd
+#
+#      - name: Submit to codecov.io
+#        uses: codecov/codecov-action@v3
+#        with:
+#          directory: build/gcov-reports
+#          fail_ci_if_error: false
+#          verbose: true
